-keep class * extends androidx.fragment.app.Fragment{}
-keepnames class * extends android.os.Parcelable
-keepnames class * extends java.io.Serializable
-keep class **.model.** { *; }
-keep class **.ui.** { *; }
-keep class **.data.** { *; }